// Generated by CoffeeScript 1.10.0
(function() {
  var Account, config, express, passport, router;

  express = require('express');

  router = express.Router();

  passport = require('passport');

  config = require('../config/config');

  Account = require('../models/account');

  router.post('/register', function(request, response, next) {
    console.log(request.body);
    return Account.register(new Account({
      username: request.body.username
    }), request.body.password, function(error, account) {
      if (error) {
        return next(error);
      }
      return passport.authenticate('local')(function(request, response, next) {
        return response.redirect('/');
      });
    });
  });

  router.post('/auth', function(request, response, next) {
    passport.authenticate('local', function(error, user, info) {
      if (error) {
        return next(error);
      }
      if (!user) {
        request.flash('message', 'authentication failed');
        return res.render('login/login', {
          title: config.title
        });
      }
      request.logIn(user, function(error) {
        if (error) {
          return next(error);
        }
        request.flash('message', 'Welcome: ' + user);
        return response.redirect('/');
      });
    })(request, response, next);
  });

  router.get('/login', function(request, response, next) {
    return response.render('login/login', {
      title: config.title,
      sessionFlash: response.locals.sessionFlash
    });
  });

  router.get('/register', function(request, response, next) {
    return response.render('login/register', {
      title: config.title,
      message: request.flash('message')
    });
  });

  router.get('/logout', function(request, response, next) {
    response.clearCookie('remember_me');
    response.logout();
    request.flash('message', 'You have logged out');
    return response.redirect('/');
  });

  module.exports = router;

}).call(this);
