// Generated by CoffeeScript 1.10.0
(function() {
  var config, express, router;

  express = require('express');

  router = express.Router();

  config = require('../config/config');

  router.get('/restricted', function(request, response, next) {
    if (request.isAuthenticated()) {
      return response.render('template.pug', {
        title: config.title,
        message: request.flash('message'),
        user: request.user
      });
    } else {
      return response.redirect('/login');
    }
  });

  module.exports = router;

}).call(this);
