// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.use(require('./authentication'));

  router.use(require('./restricted'));

  router.get('/flash', function(request, response, next) {
    request.flash('message', 'Flash is back!' + request.user);
    return response.redirect('/');
  });

  router.get('/', function(request, response, next) {
    if (request.user) {
      return response.redirect('/restricted');
    } else {
      return response.redirect('/login');
    }
  });

  module.exports = router;

}).call(this);