// Generated by CoffeeScript 1.10.0
(function() {
  var Account, LocalMongoose, Schema, config, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  LocalMongoose = require('passport-local-mongoose');

  config = require('../config/config');

  Account = new Schema({
    username: {
      type: String
    },
    password: {
      type: String
    },
    created: {
      type: Date,
      "default": Date.now
    }
  });

  Account.plugin(LocalMongoose);

  module.exports = mongoose.model('Account', Account);

}).call(this);
